### ISSUE TITLE
How to obtain metars file?

### ISSUE THREAD

**Issue by dnouri** [simonrp84/Go_Around_Detector#2]
At this moment, `OS_Funcs.py` expects a metars file to be present at `/home/proud/Desktop/GoAround_Paper/VABB_METAR`. How do I obtain this file? Thank you.

**Comment by simon-sat** [comment]
Sorry for the delayed response.
That file was manually constructed and it contains an airport ID, datetime string and unformatted METAR text like this:
```
VABB,2018-08-01 00:00,VABB 010000Z 23010G20KT 2500 HZ SCT018 SCT025 BKN090 28/25 Q1005 NOSIG
VABB,2018-08-01 00:30,VABB 010030Z 23011G21KT 2500 HZ SCT018 SCT025 BKN090 28/25 Q1005 NOSIG
VABB,2018-08-01 01:00,VABB 010100Z 23007G17KT 2500 HZ SCT018 SCT025 BKN090 28/25 Q1005 NOSIG
VABB,2018-08-01 01:30,VABB 010130Z 24013KT 2500 HZ SCT018 SCT025 BKN090 28/25 Q1005 BECMG 3000 HZ
```


One line per METAR. To my knowledge there's no automated way of grabbing historial METAR data (I'd be very interested if there was!).

For my purposes, I downloaded METARs from here: https://mesonet.agron.iastate.edu/request/download.phtml
If you have a particular airport of interest then hopefully they're also included on that site. In the scrollbox on the right labelled "Select from available data" choose the "Raw METAR" option.

**Comment by dnouri** [comment]
Thanks, that's very helpful.  I can see that the download URL on that site has query parameters that would probably make it possible to automate this:

https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py?station=VABB&data=all&year1=2020&month1=1&day1=1&year2=2020&month2=4&day2=30&tz=Etc%2FUTC&format=onlycomma&latlon=no&missing=M&trace=T&direct=no&report_type=1&report_type=2

**Comment by simon-sat** [comment]
Hm, I hadn't spotted that. Might be possible to link that up to the METAR code in this library - I'll investigate that.
